### ISSUE TITLE
How is this going. (I'm new to modding and stuff like this gets me intrigued)

### ISSUE THREAD

**Issue by Multi-Coder-24** [Fureniku/Fureniku-s-Economy#1]
I am so glad your rebuilding the economy from flenixcities that was one of my favourites. Do you have a rough idea on when this will be released. I will also try to help where I can But my modding knowledge is limited as i'm more a c# programmer.

**Comment by Fureniku** [comment]
I wouldn't recommend using this as an example if you're new to modding tbh. Most of the code was written when I didn't actually have a test environment available, so I'm currently going through debugging things that aren't working. Fureniku's Roads is a more complete mod if you're looking for examples of how some stuff works.

As for progress, the basic economy is working minus withdrawing money. Currently working on the shopping network which is hugely improved from the old FC days; you can make a shop as a singular thing all controlled from one spot, instead of having to change many individual blocks. The individual blocks still exist for buyers though.

**Comment by Multi-Coder-24** [comment]
I can Give a hand with noting what textures are broken, missing, ect. My understanding of json is good though

**Comment by Fureniku** [comment]
Most textures and models aren't done yet :) This isn't really the best place to discuss though as this isn't really an issue, you're welcome to join my Discord server here: https://discord.gg/BPzpQk2

**Comment by Multi-Coder-24** [comment]
Just a quick question if I fix Models and textures for you shall I Private message you on discord

**Comment by Fureniku** [comment]
Right now, they don't need fixing, because I've not really done that part of the mod yet. It's not needed for the code side to work, so I generally leave it until last.

Once there are builds ready for testing they will be available in the #mod-beta-releases channel, and any bugs/problems can be mentioned in the #furenikus-economy channel

**Comment by Multi-Coder-24** [comment]
BTW sent a .json model for the debit card
